# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

loader: taskgraph.loader.transform:loader

transforms:
   - taskgraph.transforms.release_deps:transforms
   - taskgraph.transforms.job:transforms
   - taskgraph.transforms.release_notifications:transforms
   - taskgraph.transforms.task:transforms

kind-dependencies:
   - beetmover-source
   - post-beetmover-checksums-dummy

job-defaults:
   description: generates checksums
   worker-type: buildbot-bridge/buildbot-bridge
   run-on-projects: []
   shipping-phase: promote
   run:
      using: buildbot
      release-promotion: true

jobs:
   firefox:
      name: release-firefox_chcksms
      shipping-product: firefox
      run:
         product: firefox
         buildername: release-{branch}-firefox_chcksms

   fennec:
      name: release-fennec_chcksms
      shipping-product: fennec
      run:
         product: fennec
         buildername: release-{branch}-fennec_chcksms

   devedition:
      name: devedition_release_chcksms
      shipping-product: devedition
      run:
         product: devedition
         buildername: release-{branch}-devedition_chcksms
