# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

rights-intro-point2a = { -brand-short-name } gibt dir keine Markenrechte oder Lizenzen an den Handelsmarken der Cliqz GmbH oder irgendeiner Partei, einschließlich ohne Einschränkungen am Namen       &quot;{ -brand-short-name }&quot; oder dem { -brand-short-name }-Logo.
# point 2.5 text for official branded builds
rights-intro-point2-5 = Manche Funktionen in { -brand-short-name }, wie z.B. der Absturzmelder, geben dir die Möglichkeit, { -brand-short-name } Feedback zu geben. Indem du das Feedback absendest, erteilst du { -brand-short-name } die Erlaubnis, das Feedback zur Verbesserung von Produkten zu nutzen, es auf Webseiten zu veröffentlichen und es zu verteilen.
# point 3 text for Cliqz branded builds
rights-intro-point3a = Cliqz respektiert deine Privatsphäre. Der Schutz deiner Daten ist uns wichtig. Als Unternehmen mit Sitz in Deutschland sind wir den besonders strengen deutschen Datenschutzgesetzen und unseren eigenen hohen Ansprüchen verpflichtet. Unser oberstes Prinzip: Cliqz speichert keinerlei Daten auf unseren Servern, anhand derer du oder dein Gerät oder dein Verhalten im Web identifizierbar wären. Erfahre mehr über <a data-l10n-name="rights-intro-point3b">Datenschutz und Privatsphäre</a>, überprüfe unsere <a data-l10n-name="rights-intro-point3c">Datenschutzerklärung</a> oder <a data-l10n-name="rights-intro-point3d">sprich direkt mit uns</a>.
# point 4 text for official branded builds
rights-intro-point4a = Einige { -brand-short-name }-Funktionen verwenden web-basierte Informationsdienste. Allerdings können wir keine Garantie dafür übernehmen, dass sie 100&#37; genau und fehlerfrei sind. Weitere Details, inklusive Informationen darüber, wie du diese Funktionen deaktivieren kannst, findest du in den <a data-l10n-name="rights-intro-point4b">Service-Bedingungen</a>.
# point 5
rights-intro-point5 = Zur Wiedergabe einiger Videoinhalte lädt { -brand-short-name } bestimmte Entschlüsselungskomponenten von Dritten herunter.
#intro paragraph for branded builds
rights2-webservices-cliqz = Der Cliqz Browser baut auf dem Mozilla Open Source Projekt auf. Cliqz nutzt web-basierte Informationsservices von Mozilla Firefox.
rights2-webservices-a = Mozilla Firefox verwendet web-basierte Informationsdienste (&quot;Services&quot;), um einige der Funktionen anbieten zu können, die dir für den Gebrauch mit der Binaryversion von Firefox unter den unten angegebenen Bedingungen zur Verfügung gestellt werden. Falls du die Dienste oder einen davon nicht verwenden möchtest oder die Bedingungen für dich nicht akzeptabel sind, kannst du die Funktion oder die Service(s) deaktivieren. Anleitungen dafür, wie du eine bestimmte Funktion oder einen Service deaktivieren kannst, findest du <a data-l10n-name="rights2-webservices-b">hier</a>. Andere Funktionen und Dienste können in den Anwendungseinstellungen deaktiviert werden.

rights-title = Über Deine Rechte
rights-intro = { -brand-full-name } ist freie und quelloffene Software, entwickelt von einer Gemeinschaft tausender Gleichgesinnter, verteilt über die gesamte Welt. Es gibt da einige Dinge, die du wissen solltest:
rights-intro-point-1 = { -brand-short-name } wird dir unter den Bedingungen der <a data-l10n-name="mozilla-public-license-link">Mozilla Public License</a> zur Verfügung gestellt. Das bedeutet, du darfst { -brand-short-name } verwenden, kopieren und an andere verteilen. Du bist auch gerne eingeladen, den Quellcode von { -brand-short-name } zu verändern und an deine eigenen Bedürfnisse anzupassen. Die Mozilla Public License gibt dir auch das Recht, deine veränderte Version an andere zu verteilen.
rights-intro-point-4-unbranded = Jegliche Datenschutzerklärungen, die für dieses Produkt gelten, sollten hier gelistet werden:
rights-intro-point-5-unbranded = Falls dieses Produkt Web-Dienste enthält, sollten gültige Service-Bedingungen für den Dienst oder die Dienste zum Bereich <a data-l10n-name="mozilla-website-services-link">Website-Dienste</a> verlinkt werden.
rights-webservices-header = { -brand-full-name } web-basierte Informationsdienste
rights-webservices = { -brand-full-name } verwendet web-basierte Informationsdienste ("Services"), um einige der Funktionen anbieten zu können, die Ihnen für den Gebrauch mit der Binaryversion von { -brand-short-name } unter den unten angegebenen Bedingungen zur Verfügung gestellt werden. Falls Sie die Dienste oder einen davon nicht verwenden möchten oder die Bedingungen für Sie nicht akzeptabel sind, können Sie die Funktion oder die Service(s) deaktivieren. Anleitungen dafür, wie Sie eine bestimmte Funktion oder einen Service deaktivieren können, finden Sie <a data-l10n-name="mozilla-disable-service-link">hier</a>. Andere Funktionen und Dienste können in den Anwendungseinstellungen deaktiviert werden.
rights-safebrowsing = <strong>SafeBrowsing: </strong>Das Deaktivieren von SafeBrowsing wird nicht empfohlen, da Sie auf unsichere Seiten stoßen könnten.  Wenn Sie diese Funktion komplett deaktivieren möchten, führen Sie bitte folgende Schritte aus:
rights-safebrowsing-term-1 = Öffnen Sie das Einstellungen-Fenster
rights-safebrowsing-term-2 = Wählen Sie den Tab Sicherheit
rights-safebrowsing-term-3 = Wählen Sie die Option "{ enableSafeBrowsing-label }" ab
enableSafeBrowsing-label = Gefährliche und betrügerische Inhalte blockieren
rights-safebrowsing-term-4 = SafeBrowsing ist nun deaktiviert
rights-locationawarebrowsing = <strong>Standortbezogenes Browsing: </strong>ist immer eine Opt-in-Funktion.  Standortdaten werden niemals ohne Ihre Erlaubnis gesendet.  Wenn Sie diese Funktion komplett deaktivieren möchten, führen Sie bitte folgende Schritte aus:
rights-locationawarebrowsing-term-1 = Rufen Sie in der Adressleiste<code>about:config</code>
rights-locationawarebrowsing-term-2 = auf. Tippen Sie dann geo.enabled
rights-locationawarebrowsing-term-3 = Führen Sie einen Doppelklick auf geo.enabled aus
rights-locationawarebrowsing-term-4 = Standortbezogenes Browsing ist nun deaktiviert
rights-webservices-unbranded = Ein Überblick über die verwendeten Website-Dienste und eine Anleitung, wie sie deaktiviert werden können, wenn das vorgesehen ist, sollte hier eingefügt werden.
rights-webservices-term-unbranded = Jegliche Bedingungen für die Dienste, die dieses Produkt verwendet, sollten hier gelistet werden.
rights-webservices-term-1 = Mozilla und die Mitwirkenden, Lizenzgeber und Partner versuchen die genausten und aktuellsten Services zur Verfügung zu stellen. Allerdings kann nicht garantiert werden, dass die Daten umfassend und fehlerfrei sind.  Beispielsweise könnte der SafeBrowsing-Service manche riskanten Websites als sicher einstufen und manche sicheren Websites fälschlicherweise als riskant. Und für standortbezogene Dienste gilt, dass alle Standortdaten, die von unseren Service-Providern geliefert werden, nur Schätzungen darstellen, und weder wir noch unsere Service-Provider garantieren für die Genauigkeit der Standortdaten.
rights-webservices-term-2 = Mozilla kann die Dienste nach eigenem Ermessen abschalten oder verändern.
rights-webservices-term-3 = Du bist eingeladen, diese Dienste mit der dazugehörigen Firefox-Version zu verwenden, und Mozilla erteilt dir die Rechte dies zu tun. Mozilla und ihre Lizenzgeber behalten sich alle anderen Rechte an den Diensten vor. Diese Bedingungen beabsichtigen nicht, jegliche Rechte einzuschränken, die von Open-Source-Lizenzen gewährt werden, die auf Firefox und entsprechende Quellcode-Versionen von Firefox anwendbar sind.
rights-webservices-term-4 = <strong>Die Dienste werden "wie es ist" zur Verfügung gestellt. Mozilla, ihre Mitwirkenden, Lizenzgeber und Distributoren gewähren keinerlei Gewährleistung, weder ausdrücklich noch implizit, einschließlich – aber nicht begrenzt auf – Marktreife oder Verwendbarkeit für einen bestimmten Zweck. Das volle Risiko bezüglich der Auswahl des für dich richtigen Dienstes und die Qualität und Leistungsfähigkeit des Dienstes liegt bei dir. Manche Gerichtsbarkeiten erlauben nicht den Ausschluss oder die Eingrenzung von implizierten Risiken, so dass dieser Haftungsausschluss möglicherweise nicht für dich gilt.</strong>
rights-webservices-term-5 = <strong>In keinem Fall, außer wenn durch geltendes Recht gefordert, sind Mozilla, ihre Mitwirkenden, Lizenzgeber oder Distributoren für irgendwelchen indirekten oder speziellen Schäden, Schäden durch Seiteneffekte (Nebenwirkungen) oder Folgeschäden, die aus der Benutzung von Firefox oder den Diensten folgen, haftbar. Die gesamte Haftbarkeit unter diesen Bedingungen beschränkt sich auf maximal $500 (fünfhundert Dollar). Manche Gerichtsbarkeiten erlauben nicht den Ausschluss oder die Eingrenzung von bestimmten Risiken, so dass diese Ausschlüsse oder Eingrenzungen möglicherweise nicht für dich gelten.</strong>
rights-webservices-term-6 = Mozilla kann diese Bedingungen bei Bedarf von Zeit zu Zeit aktualisieren. Diese Bedingungen können nicht ohne eine schriftliche Zusicherung von Mozilla verändert oder aufgehoben werden.
rights-webservices-term-7 = Diese Bedingungen werden durch die Gesetze des Staates Kalifornien, USA, geschützt, ausschließlich den damit in Konflikt stehenden Rechtsvorschriften. Sollten einzelne Bestimmungen dieser Bedingungen unwirksam oder undurchführbar sein, bleibt davon die Wirksamkeit der anderen Bedingungen unberührt. Falls ein Konflikt bestehen sollte, zwischen der übersetzen Version dieser Bedingungen und der englischsprachigen Version, gelten die Bedingungen der englischsprachigen Version.
