[package]
name = "u2fhid"
version = "0.1.0"
authors = ["Kyle Machulis <kyle@nonpolynomial.com>", "J.C. Jones <jc@mozilla.com>", "Tim Taubert <ttaubert@mozilla.com>"]

[target.'cfg(target_os = "linux")'.dependencies]
libudev = "^0.2"

[target.'cfg(target_os = "macos")'.dependencies]
core-foundation-sys = "0.3.1"

[target.'cfg(target_os = "windows")'.dependencies]
winapi = "0.2.8"

[dependencies]
rand = "0.3"
log = "0.3"
env_logger = "0.4.1"
libc = "^0.2"
boxfnonce = "0.0.3"
runloop = "0.1.0"
bitflags = "1.0"

[dev-dependencies]
rust-crypto = "^0.2"
base64 = "^0.4"
