# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

loader: taskgraph.loader.transform:loader

kind-dependencies:
  - packages

transforms:
  - taskgraph.transforms.docker_image:transforms
  - taskgraph.transforms.task:transforms

# make a task for each docker-image we might want.  For the moment, since we
# write artifacts for each, these are whitelisted, but ideally that will change
# (to use subdirectory clones of the proper directory), at which point we can
# generate tasks for every docker image in the directory, secure in the
# knowledge that unnecessary images will be omitted from the target task graph
jobs:
  image_builder:
    symbol: I(ib)
  desktop1604-test:
    symbol: I(dt16t)
  desktop-build:
    symbol: I(db)
  valgrind-build:
    symbol: I(vb)
  toolchain-build:
    symbol: I(toolchain)
    packages:
      - deb7-cmake
      - deb7-git
      - deb7-make
      - deb7-mercurial
      - deb7-ninja
      - deb7-python
      - deb7-xz-utils
  debian7-amd64-build:
    symbol: I(deb7)
    definition: debian7-build
    packages:
      - deb7-git
      - deb7-make
      - deb7-mercurial
      - deb7-python
      - deb7-valgrind
      - deb7-xz-utils
    args:
      ARCH: amd64
  debian7-i386-build:
    symbol: I(deb7-32)
    definition: debian7-build
    packages:
      - deb7-git
      - deb7-make
      - deb7-mercurial
      - deb7-python
      - deb7-valgrind
      - deb7-xz-utils
    args:
      ARCH: i386
  lint:
    symbol: I(lnt)
  android-build:
    symbol: I(agb)
  index-task:
    symbol: I(idx)
  funsize-update-generator:
    symbol: I(pg)
  google-play-strings:
    symbol: I(gps)
  funsize-balrog-submitter:
    symbol: I(fbs)
  beet-mover:
    symbol: I(bm)
  update-verify:
    symbol: I(uv)
  diffoscope:
    symbol: I(diff)
