# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

loader: taskgraph.loader.transform:loader

transforms:
   - taskgraph.transforms.release_deps:transforms
   - taskgraph.transforms.release_balrog_publishing:transforms
   - taskgraph.transforms.job:transforms
   - taskgraph.transforms.release_notifications:transforms
   - taskgraph.transforms.task:transforms

kind-dependencies:
   - release-bouncer-check

job-defaults:
   description: Schedule publishing in balrog
   worker-type: buildbot-bridge/buildbot-bridge
   run-on-projects: []
   shipping-phase: ship
   run:
      using: buildbot
      release-promotion: true

jobs:
   firefox:
      name: release-firefox_schedule_publishing_in_balrog
      shipping-product: firefox
      run:
         product: firefox
         buildername: release-{branch}-firefox_schedule_publishing_in_balrog
         channels:
            by-project:
               birch: release
               maple: beta
               mozilla-beta: beta
               mozilla-release: release
               mozilla-esr52: esr
               mozilla-esr59: esr
               default: unknown

   devedition:
      name: release-devedition_schedule_publishing_in_balrog
      shipping-product: devedition
      run:
         product: devedition
         buildername: release-{branch}-devedition_schedule_publishing_in_balrog
         channels: aurora
