[package]
name = "webrender_bindings"
version = "0.1.0"
authors = ["The Mozilla Project Developers"]
license = "MPL-2.0"

[dependencies]
rayon = "1"
thread_profiler = "0.1.1"
euclid = { version = "0.17", features = ["serde"] }
app_units = "0.6"
gleam = "0.4.32"
log = "0.4"

[dependencies.webrender]
path = "../webrender"
version = "0.57.2"
default-features = false
features = ["capture"]

[target.'cfg(target_os = "windows")'.dependencies]
dwrote = "0.4.1"

[target.'cfg(target_os = "macos")'.dependencies]
core-foundation = "0.5"
core-graphics = "0.13"
foreign-types = "0.3.0"

