[package]
name = "xpcom"
version = "0.1.0"
authors = ["michael@thelayzells.com"]

[dependencies]
libc = "0.2"
nsstring = { path = "../../../servo/support/gecko/nsstring" }
nserror = { path = "../nserror" }
xpcom_macros = { path = "xpcom_macros" }
