# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

loader: taskgraph.loader.transform:loader

transforms:
   - taskgraph.transforms.release_deps:transforms
   - taskgraph.transforms.release_snap:transforms
   - taskgraph.transforms.release_notifications:transforms
   - taskgraph.transforms.task:transforms

kind-dependencies:
   - post-beetmover-dummy

job-defaults:
   description: Generates snap image
   run-on-projects: []  # to make sure this never runs as part of CI
   shipping-phase: promote
   scopes:
      by-project:
         mozilla-beta: ["secrets:get:project/releng/snapcraft/firefox/edge"]
         mozilla-release: ["secrets:get:project/releng/snapcraft/firefox/candidate"]
         default: []
   treeherder:
      platform: linux64/opt
      kind: build
      tier: 3
   worker-type: aws-provisioner-v1/gecko-{level}-b-linux
   worker:
      implementation: docker-worker
      os: linux
      max-run-time: 7200
      docker-image: mozillareleases/firefox-snapcraft@sha256:107cc7a89d45ce6df30f44fe0dfd0b375b3ab443b75e92efc77c4f7bc5da8717
      artifacts:
         - name: public/build
           type: directory
           path: /home/worker/artifacts/
      command:
         - /bin/bash
         - -cx
         - >
           apt-get update &&
           apt-get dist-upgrade -y &&
           curl -o scripts.tar.bz2 {config_params[head_repository]}/archive/{config_params[head_rev]}.tar.bz2/taskcluster/docker/firefox-snap/ &&
           mkdir scripts &&
           tar xvfj scripts.tar.bz2 -C scripts --strip-components 4 &&
           cd scripts &&
           ./runme.sh
      env:
         VERSION: "{release_config[version]}"
         BUILD_NUMBER: "{release_config[build_number]}"
         PUSH_TO_CHANNEL:
            by-project:
               # The snap stores exposes 4 channels: edge, beta, candidate, release.
               # Let's use edge and candidate for QE to test. Then, on the Snap Store UI,
               # we can promote builds to beta and release, respectively.
               # For more info: https://docs.snapcraft.io/reference/channels
               mozilla-beta: edge
               mozilla-release: candidate
               default: ""
         CANDIDATES_DIR:
            by-project:
               maple:
                  https://net-mozaws-stage-delivery-firefox.s3.amazonaws.com/pub/{task[shipping-product]}/candidates
               default:
                  https://net-mozaws-prod-delivery-firefox.s3.amazonaws.com/pub/{task[shipping-product]}/candidates
         LC_ALL: C.UTF-8
         LANG: C.UTF-8
         L10N_CHANGESETS: "{config_params[head_repository]}/raw-file/{config_params[head_rev]}/browser/locales/l10n-changesets.json"
      taskcluster-proxy: true

jobs:
   firefox:
      shipping-product: firefox
      treeherder:
         symbol: Snap(BF)
