$inherits:
  from: 'tasks/builds/b2g_phone_base.yml'
  variables:
    build_name: 'nexus-4-user'
    build_type: 'opt'
task:
  workerType: flame-kk
  scopes:
    - 'docker-worker:cache:build-nexus-4-user'
  metadata:
    name: '[TC] B2G Nexus 4 User'

  payload:
    cache:
      build-nexus-4-user: /home/worker/object-folder
    env:
      TARGET: 'nexus-4'
      DEBUG: 0
    command:
      - >
        checkout-gecko workspace &&
        cd ./workspace/gecko/testing/taskcluster/scripts/phone-builder &&
        buildbot_step 'Build' ./build-phone.sh $HOME/workspace
  extra:
    treeherderEnv:
      - production
      - staging
    treeherder:
      symbol: B
      groupSymbol: Nexus 4
      groupName: Nexus 4 Device Image
      machine:
        platform: b2g-device-image
    locations:
      img: 'private/build/nexus-4.zip'
