$inherits:
  from: 'tasks/builds/b2g_emulator_base.yml'
  variables:
    build_name: 'emulator-kk'
    build_type: 'opt'
task:
  workerType: emulator-kk
  routes:
    - 'index.buildbot.branches.{{project}}.emulator-kk'
    - 'index.buildbot.revisions.{{head_rev}}.{{project}}.emulator-kk'
  scopes:
    - 'docker-worker:cache:workspace-emulator-kk-opt'
    - 'docker-worker:cache:workspace-emulator-kk-opt-objdir-gecko-{{project}}'
  metadata:
    name: '[TC] B2G KK Emulator (Opt)'

  extra:
    treeherderEnv:
      - production
      - staging
    treeherder:
      # Disable "TC" prefix...
      groupSymbol: "?"
      machine:
        platform: b2g-emu-kk

  payload:
    cache:
      workspace-emulator-kk-opt: /home/worker/workspace
      workspace-emulator-kk-opt-objdir-gecko-{{project}}: /home/worker/objdir-gecko
    env:
      TARGET: 'emulator-kk'
      TOOLTOOL_MANIFEST: 'b2g/config/emulator-kk/releng-emulator-kk.tt'
