$inherits:
  from: 'tasks/builds/b2g_emulator_x86_base.yml'
  variables:
    build_name: 'emulator-x86-kk'
    build_type: 'debug'
task:
  workerType: emulator-x86-kk
  scopes:
    - 'docker-worker:cache:workspace-emulator-kk-x86-debug'
    - 'docker-worker:cache:workspace-emulator-kk-x86-debug-objdir-gecko-{{project}}'
  metadata:
    name: '[TC] B2G KK X86 Emulator (Debug)'

  extra:
    treeherderEnv:
      - production
      - staging
    treeherder:
      # Disable "TC" prefix...
      groupSymbol: "?"
      collection:
        debug: true
      machine:
        platform: b2g-emu-x86-kk

  payload:
    cache:
      workspace-emulator-kk-x86-debug: /home/worker/workspace
      workspace-emulator-kk-x86-debug-objdir-gecko-{{project}}: /home/worker/objdir-gecko
    env:
      TARGET: 'emulator-x86-kk'
      TOOLTOOL_MANIFEST: 'b2g/config/emulator-x86-kk/releng-emulator-kk.tt'
      B2G_DEBUG: 1
