$inherits:
  from: 'tasks/builds/b2g_emulator_base.yml'
  variables:
    build_name: 'emulator-ics'
    build_type: 'debug'
task:
  workerType: emulator-ics-debug
  scopes:
    - 'docker-worker:cache:workspace-emulator-ics-debug'
    - 'docker-worker:cache:workspace-emulator-ics-debug-objdir-gecko-{{project}}'
  metadata:
    name: '[TC] B2G Emulator ICS Debug'
  extra:
    treeherder:
      collection:
        debug: true
      machine:
        platform: b2g-emu-ics


  payload:
    cache:
      workspace-emulator-ics-debug: /home/worker/workspace
      workspace-emulator-ics-debug-objdir-gecko-{{project}}: /home/worker/objdir-gecko
    env:
      TARGET: 'emulator'
      B2G_DEBUG: 1
      TOOLTOOL_MANIFEST: 'b2g/config/emulator-ics/releng-emulator-ics.tt'
