$inherits:
  from: 'tasks/builds/b2g_emulator_base.yml'
  variables:
    build_name: 'emulator-jb'
    build_type: 'opt'
task:
  workerType: emulator-jb
  scopes:
    - 'docker-worker:cache:workspace-emulator-jb-opt'
    - 'docker-worker:cache:workspace-emulator-jb-opt-objdir-gecko-{{project}}'
  metadata:
    name: '[TC] B2G JB Emulator: (Opt)'

  extra:
    treeherderEnv:
      - production
      - staging
    # Disable "TC" prefix...
    treeherder:
      groupSymbol: "?"
      machine:
        platform: b2g-emu-jb

  payload:
    cache:
      workspace-emulator-jb-opt: /home/worker/workspace
      workspace-emulator-jb-opt-objdir-gecko-{{project}}: /home/worker/objdir-gecko
    env:
      TARGET: 'emulator-jb'
      TOOLTOOL_MANIFEST: 'b2g/config/emulator-jb/releng-emulator-jb.tt'
