[package]
name = "style_derive"
version = "0.0.1"
authors = ["The Servo Project Developers"]
license = "MPL-2.0"
publish = false

[lib]
path = "lib.rs"
proc-macro = true

[dependencies]
darling = "0.3"
quote = "0.4.2"
syn = { version = "0.12.12", features = ["visit"] }
synstructure = "0.7"
