# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

loader: taskgraph.loader.transform:loader

transforms:
   - taskgraph.transforms.release_deps:transforms
   - taskgraph.transforms.job:transforms
   - taskgraph.transforms.release_notifications:transforms
   - taskgraph.transforms.task:transforms

kind-dependencies:
   - release-bouncer-check

job-defaults:
   description: Update bouncer aliases job
   worker-type: buildbot-bridge/buildbot-bridge
   run-on-projects: []
   shipping-phase: ship
   run:
      using: buildbot
      release-promotion: true
   worker:
      properties:
         tuxedo_server_url:
            by-project:
               mozilla-beta: https://bounceradmin.mozilla.com/api
               mozilla-release: https://bounceradmin.mozilla.com/api
               maple: https://admin-bouncer-releng.stage.mozaws.net/api
               default: http://localhost/api

jobs:
   fennec:
      name: fennec_release_bouncer_aliases
      shipping-product: fennec
      run:
         product: fennec
         buildername: release-{branch}-fennec_bouncer_aliases

   firefox:
      name: firefox_release_bouncer_aliases
      shipping-product: firefox
      run:
         product: firefox
         buildername: release-{branch}-firefox_bouncer_aliases

   devedition:
      name: devedition_release_bouncer_aliases
      shipping-product: devedition
      run:
         product: devedition
         buildername: release-{branch}-devedition_bouncer_aliases
