[package]
name = "webdriver"
version = "0.33.0"
authors = ["Mozilla <tools-marionette@lists.mozilla.org>"]
description = "Library implementing the wire protocol for the W3C WebDriver specification."
keywords = ["webdriver", "browser", "automation", "protocol", "w3c"]
documentation = "https://docs.rs/webdriver"
repository = "https://hg.mozilla.org/mozilla-central/file/tip/testing/webdriver"
readme = "README.md"
license = "MPL-2.0"

[dependencies]
cookie = { version = "0.10", default-features = false }
hyper = "0.10"
log = "0.3"
regex = "0.2"
rustc-serialize = "0.3"
time = "0.1"
url = "1"
