[package]
name = "mozprofile"
version = "0.3.0"
authors = ["Mozilla Tools and Automation <auto-tools@mozilla.com>"]
description = "Library for working with Mozilla profiles."
repository = "https://hg.mozilla.org/mozilla-central/file/tip/testing/mozbase/rust/mozprofile"
license = "MPL-2.0"

[dependencies]
tempdir = "0.3.4"
