# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

loader: taskgraph.loader.transform:loader

transforms:
   - taskgraph.transforms.release_deps:transforms
   - taskgraph.transforms.release_balrog_publishing:transforms
   - taskgraph.transforms.job:transforms
   - taskgraph.transforms.release_notifications:transforms
   - taskgraph.transforms.task:transforms

kind-dependencies:
   - post-balrog-dummy
   - post-beetmover-dummy
   - release-updates-builder

job-defaults:
   description: Schedule publishing in balrog
   worker-type: buildbot-bridge/buildbot-bridge
   run-on-projects: []
   shipping-phase: ship
   run:
      using: buildbot
      release-promotion: true

jobs:
   firefox-secondary-rc:
      name: release-firefox_schedule_publishing_in_balrog
      shipping-product: firefox
      run:
         product: firefox
         buildername: release-{branch}-firefox_schedule_publishing_in_balrog
         channels:
            by-project:
               birch: beta
               mozilla-release: beta
               default: unknown
