[package]
name = "jstraceable_derive"
version = "0.0.1"
authors = ["The Servo Project Developers"]
license = "MPL-2.0"
publish = false

[lib]
path = "lib.rs"
proc-macro = true

[dependencies]
quote = "0.4.2"
syn = "0.12.12"
synstructure = "0.7"
