[package]
name = "audioipc"
version = "0.2.4"
authors = [
        "Matthew Gregan <kinetik@flim.org>",
        "Dan Glastonbury <dan.glastonbury@gmail.com>"
        ]
description = "Remote Cubeb IPC"

[dependencies]
cubeb = "0.5.2"
bincode = "1.0"
bytes = "0.4"
futures = "0.1.18"
iovec = "0.1"
libc = "0.2"
log = "^0.3.6"
memmap = "0.5.2"
scoped-tls = "0.1"
serde = "1.*.*"
serde_derive = "1.*.*"
tokio-core = "0.1"
tokio-io = "0.1"
tokio-uds = "0.1.7"

[dependencies.error-chain]
version = "0.11.0"
default-features = false
